#include "headers/mainwindow.h"
#include "headers/thirdwindow.h"
#include "headers/forthwindow.h"
#include "headers/fifthwindow.h"
#include "headers/sixthwindow.h"
#include "headers/seventhwindow.h"
#include "headers/eighthwindow.h"
#include "headers/ninthwindow.h"
#include "headers/tenthwindow.h"
#include "headers/eleventhwindow.h"
#include "headers/twelfthwindow.h"
#include "headers/thirteenthwindow.h"
#include "headers/fourteenthwindow.h"
#include "headers/fifteenthwindow.h"

#include "headers/pathwindow.h"
